---
title: "Yelp API USCLAP"
author: "Stephen Trippy"
date: "6/12/2021"
output: 
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = TRUE)
```

Libraries
```{r}
#copied from previous projects

library("dplyr")
library("jsonlite")
library("httr")
library("readxl")
library("tidyr")
library("ggplot2")
library("devtools")
library("RCurl")
library("sf")

#install_github('gavinrozzi/zipcodeR')
library("zipcodeR")
#install_github('arilamstein/choroplethrZip@v1.5.0')
library("choroplethrZip")
```

```{r}
county_codes <- read.csv("zcta_county_rel_10.csv", colClasses = c("ZCTA5" = "character", "STATE" = "character", "COUNTY" = "character", "GEOID" = "character")) #specifying read as character allows for first column to keep leading zeroes

```

```{r}
zip_demographic_data <- read_excel('zipcode_census_data.xlsx', sheet = 'nation', na = ".")
zip_demographic_data$Zip <- as.character(zip_demographic_data$Zip)
for (i in 1:length(zip_demographic_data$Zip)){
  if (as.numeric(zip_demographic_data$Zip[i]) < 10000){
    zip_demographic_data$Zip[i] <- paste0("0", zip_demographic_data$Zip[i])
  }
}
```

```{r}
county_data_by_zip <- county_codes %>%
  select(GEOID, ZCTA5) %>% 
  rename(Zip = ZCTA5)

county_data_by_zip <- inner_join(county_data_by_zip, zip_demographic_data, by = "Zip")
#Some of the zip codes in county_data_by_zips had no demographic data, so i decided to
#inner_join. 
#I could left join though, if I really felt like keeping all of the restaurant data
#from these zip codes

harris_data_by_zip <- filter(county_data_by_zip, GEOID == "48201")
cook_data_by_zip <- filter(county_data_by_zip, GEOID == "17031")
la_data_by_zip <- filter(county_data_by_zip, GEOID == "06037")
maricopa_data_by_zip <- filter(county_data_by_zip, GEOID == "04013")
sandiego_data_by_zip <- filter(county_data_by_zip, GEOID == "06073")
orange_data_by_zip <- filter(county_data_by_zip, GEOID == "06059")
miamidade_data_by_zip <- filter(county_data_by_zip, GEOID == "12086")
dallas_data_by_zip <- filter(county_data_by_zip, GEOID == "48113")
kings_data_by_zip <- filter(county_data_by_zip, GEOID == "36047")
riverside_data_by_zip <- filter(county_data_by_zip, GEOID == "06065")
```

```{r}
#Loading the API key from a separate file
source("yelp_api_key.R") #allows yelp_key to be available
#info in order to make GET request, using API key as a header
base_uri <- "https://api.yelp.com/v3"
endpoint <- "/businesses/search"
search_uri <- paste0(base_uri, endpoint)
```

```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(harris_data_by_zip$Zip)){
  zip_code_n <- harris_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}
```

```{r}
#take all of the data we've just extracted. Now bind it into one masterlist
harris_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
harris_masterlist <- harris_masterlist[!duplicated(harris_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
harris_masterlist <- harris_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

Note: I guess 77507 is one zip code in harris county that doesn't have any demographic data. Hence why it shows up as black. 

```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(cook_data_by_zip$Zip)){
  zip_code_n <- cook_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}
```

```{r}
#take all of the data we've just extracted. Now bind it into one masterlist
cook_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
cook_masterlist <- cook_masterlist[!duplicated(cook_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
cook_masterlist <- cook_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

Next is la county
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(la_data_by_zip$Zip)){
  zip_code_n <- la_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}
```

```{r}
#take all of the data we've just extracted. Now bind it into one masterlist
la_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
la_masterlist <- la_masterlist[!duplicated(la_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
la_masterlist <- la_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

maricopa county
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(maricopa_data_by_zip$Zip)){
  zip_code_n <- maricopa_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}

#take all of the data we've just extracted. Now bind it into one masterlist
maricopa_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
maricopa_masterlist <- maricopa_masterlist[!duplicated(maricopa_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
maricopa_masterlist <- maricopa_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

san diego county
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(sandiego_data_by_zip$Zip)){
  zip_code_n <- sandiego_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}

#take all of the data we've just extracted. Now bind it into one masterlist
sandiego_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
sandiego_masterlist <- sandiego_masterlist[!duplicated(sandiego_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
sandiego_masterlist <- sandiego_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

orange county 
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(orange_data_by_zip$Zip)){
  zip_code_n <- orange_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}

#take all of the data we've just extracted. Now bind it into one masterlist
orange_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
orange_masterlist <- orange_masterlist[!duplicated(orange_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
orange_masterlist <- orange_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

miami-dade county 
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(miamidade_data_by_zip$Zip)){
  zip_code_n <- miamidade_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}

#take all of the data we've just extracted. Now bind it into one masterlist
miamidade_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
miamidade_masterlist <- miamidade_masterlist[!duplicated(miamidade_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
miamidade_masterlist <- miamidade_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

dallas county 
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(dallas_data_by_zip$Zip)){
  zip_code_n <- dallas_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}

#take all of the data we've just extracted. Now bind it into one masterlist
dallas_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
dallas_masterlist <- dallas_masterlist[!duplicated(dallas_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
dallas_masterlist <- dallas_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

kings county
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(kings_data_by_zip$Zip)){
  zip_code_n <- kings_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}

#take all of the data we've just extracted. Now bind it into one masterlist
kings_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
kings_masterlist <- kings_masterlist[!duplicated(kings_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
kings_masterlist <- kings_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```

riverside county
```{r}
zip_restaurant_list = list()
restaurant_list = list()

#the following loop iterates through the list of valid zip codes
#and sets the location query equal to each zip code in the list
for(j in 1:length(riverside_data_by_zip$Zip)){
  zip_code_n <- riverside_data_by_zip$Zip[j]
  
    query_params <- list(
      term = "Restaurants",
      location = zip_code_n, #zip code at position 'j' in the dataframe
      sort_by = "distance",
      limit = 50
    )
    response <- GET(
      search_uri, 
      query = query_params, 
      add_headers(Authorization = paste("bearer", yelp_key))
    )
    response_text <- content(response, type = "text")
    response_data <- fromJSON(response_text)
    restaurants <- flatten(response_data$businesses)
  
    #each set of restaurants pulled is added to the restaurant list
    restaurant_list[[j]] <- restaurants
}

#take all of the data we've just extracted. Now bind it into one masterlist
riverside_masterlist <- bind_rows(restaurant_list) 

#remove the duplicate restaurants (each restaurant should have a unique id)
riverside_masterlist <- riverside_masterlist[!duplicated(riverside_masterlist$id), ]

#renaming the zip code column will make it so that we can join with the
#harris_data_by_zip dataset later. We also set this variable's type to double 
#for the same reason
riverside_masterlist <- riverside_masterlist %>% rename(Zip = location.zip_code) 
#masterlist$zip_code <- as.double(masterlist$zip_code) not needed I don't think..
```
